// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Data;

#nullable disable

namespace WebApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApplication.Models.ShortLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClickCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ShortUrl")
                        .IsUnique();

                    b.ToTable("ShortLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClickCount = 0,
                            CreatedAt = new DateTime(2025, 2, 13, 7, 49, 53, 37, DateTimeKind.Utc).AddTicks(2091),
                            OriginalUrl = "https://blogs-images.forbes.com/ceciliarodriguez/files/2018/06/00000015_p.jpg",
                            ShortUrl = "772f7fac"
                        },
                        new
                        {
                            Id = 2,
                            ClickCount = 0,
                            CreatedAt = new DateTime(2025, 2, 13, 7, 49, 53, 37, DateTimeKind.Utc).AddTicks(2093),
                            OriginalUrl = "https://s0.rbk.ru/v6_top_pics/media/img/5/13/756372136012135.jpg",
                            ShortUrl = "60c0ed2f"
                        },
                        new
                        {
                            Id = 3,
                            ClickCount = 0,
                            CreatedAt = new DateTime(2025, 2, 13, 7, 49, 53, 37, DateTimeKind.Utc).AddTicks(2097),
                            OriginalUrl = "https://i.pinimg.com/736x/38/1e/0f/381e0f5a84c95c81f2d470d71ee9c2b4.jpg",
                            ShortUrl = "6a54607f"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
